name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Doclerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiters email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    defalut: ${{ github.actor }}